tasks:
  - name: Build migration program
    init: |
      cd ./examples/simple/migrations
      go build .
    command: |
      exit 0

  - name: MySQL
    env:
      DB_CONNECTION: "root:password@tcp(localhost:3306)/gobblr"
      DB_TYPE: mysql
    command: |
      docker run \
        -e MYSQL_ROOT_PASSWORD=password \
        -e MYSQL_DATABASE=gobblr \
        --rm \
        -p 3306:3306 \
        --name mysql \
        mysql &

      ./examples/simple/migrations/simple

  - name: MongoDB
    command: |
      docker run \
        --rm \
        -p 27017:27017 \
        --name mongodb \
        mongo

  - name: PostgreSQL
    command: |
      docker run \
        -e POSTGRES_PASSWORD=password \
        --rm \
        -p 5432:5432 \
        --name pgsql \
        postgres

  - before: |
      curl -sfL gpm.simonemms.com | bash

      gpm install cobra-cli
    init: |
      go install ./...
    command: |
      # Install commitlint
      npm i -g @commitlint/{config-conventional,cli}

      # Install husky
      npm i -g husky

      # Activate hooks
      husky install

      # Copy .cobra.yaml to $HOME
      cp .cobra.yaml $HOME/.cobra.yaml

      export GIT_REPO="${GITPOD_WORKSPACE_CONTEXT_URL/https:\/\//}"
      export PROJECT_NAME="${GIT_REPO##*/}"

      if [ ! -f "go.mod" ]; then
        echo "Creating Go module"
        go mod init "$GIT_REPO"
      fi
      if [ ! -f "main.go" ]; then
        echo "Create Cobra project"
        cobra-cli init
        go mod tidy
      fi

vscode:
  extensions:
    - donjayamanne.git-extension-pack
    - EditorConfig.EditorConfig
    - golang.go

ports:
  - port: 3306
    name: MySQL
    visibility: private
