FROM golang AS builder
ARG GIT_COMMIT
ARG GIT_REPO
ARG PROJECT_NAME
ARG VERSION
WORKDIR /app
ADD . .
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV PROJECT_NAME="${PROJECT_NAME}"
RUN go build \
  -ldflags \
  "-X $GIT_REPO/cmd.Version=$VERSION -X $GIT_REPO/cmd.GitCommit=$GIT_COMMIT"
ENTRYPOINT /app/${PROJECT_NAME}

FROM alpine
ARG PROJECT_NAME
ENV PROJECT_NAME="${PROJECT_NAME}"
RUN apk --no-cache add ca-certificates
WORKDIR /app
COPY --from=builder /app/$PROJECT_NAME /app
ENTRYPOINT /app/${PROJECT_NAME}
